api/urls.py
from django.urls import path
from . import views
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [
    path('', views.getRoutes),
    path('projects/', views.getProjects),
    path('project/<str:pk>', views.getProject),
    path('projects/<str:pk>/vote/', views.projectVote),
    path('users/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('users/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('remove-tag/', views.removeTag, name='remove-tag'),

]

auth/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('core.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecom/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', views.HomeView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('profile/', views.ProfileView.as_view(), name='profile')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.registerUser, name = 'register'),

    path('', views.profiles, name='profiles'),
    path('profile/<str:pk>', views.userProfile, name='user-profile'),
    path('account/', views.userAccount, name='account'),

    path('edit-account/', views.editAccount, name='edit-account'),
    path('create-skill/', views.createSkill, name='create-skill'),
    path('update-skill/<str:pk>', views.updateSkill, name='update-skill'),
    path('delete-skill/<str:pk>', views.deleteSkill, name='delete-skill'),

    path('inbox/', views.inbox, name='inbox'),
    path('message/<str:pk>', views.viewMessage, name='message'),
    path('create-message/<str:pk>', views.createMessage, name='create-message'),
    
]

users/models.py
from email.policy import default
from signal import signal
from unicodedata import name
from django.db import models
from django.contrib.auth.models import User
import uuid


class Profile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    email = models.EmailField(max_length=500, blank=True, null=True)
    username = models.CharField(max_length=200, blank=True, null=True)
    short_intro = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    profile_image = models.ImageField(
        null=True, blank=True, upload_to='profiles/', default='profiles/user-default.png')
    social_github = models.CharField(max_length=200, blank=True, null=True)
    social_twitter = models.CharField(max_length=200, blank=True, null=True)
    social_linkedin = models.CharField(max_length=200, blank=True, null=True)
    social_youtube = models.CharField(max_length=200, blank=True, null=True)
    social_website = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    location = models.CharField(max_length=200, blank=True, null=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return str(self.username)

    class Meta:
        ordering=['created']

    @property
    def imageURL(self):
        try:
            url=self.profile_image.url
        except:
            url=''
        return url


class Skill(models.Model):
    owner = models.ForeignKey(
        Profile, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return str(self.name)

class Message(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True)
    recipient = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True, related_name="messages")
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    subject = models.CharField(max_length=200, null=True, blank=True)
    body = models.TextField()
    is_read = models.BooleanField(default=False, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return str(self.subject)
    
    class Meta:
        ordering=['is_read', '-created']
    

accounts/forms.py
from django import forms
from .models import Account, Profile


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter Password',
    }))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm Password',
    }))

    class Meta:
        model = Account
        fields = ['first_name', 'last_name', 'phone_number', 'email']

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['placeholder'] = 'Enter first name'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Enter last name'
        self.fields['phone_number'].widget.attrs['placeholder'] = 'Enter phone number'
        self.fields['email'].widget.attrs['placeholder'] = 'Enter email'
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        if password != confirm_password:
            raise forms.ValidationError("Password does not match!")


class UserForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['first_name', 'last_name', 'phone_number']
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

class ProfileForm(forms.ModelForm):
    profile_picture = forms.ImageField(required=False, error_messages={'invalid':("Image files only")}, widget=forms.FileInput)
    class Meta:
        model = Profile
        fields = ['address_line_1', 'address_line_2',
                  'country', 'state', 'city', 'profile_picture']

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

accounts/views.py
from email.message import EmailMessage
from django.shortcuts import get_object_or_404, redirect, render

from accounts.models import Account,Profile

from orders.models import Order,OrderProduct
from .forms import RegistrationForm, UserForm,ProfileForm
from django.contrib import messages
from django.contrib import auth
from django.contrib.auth.decorators import login_required

from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage
from carts.views import _cart_id
from carts.models import Cart,CartItem

import requests as requestsLib

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            phone_number = form.cleaned_data['phone_number']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']

            username = email.split('@')[0]

            user = Account.objects.create_user(
                first_name=first_name,
                last_name=last_name,
                username=username,
                email=email,
                password=password,
            )
            user.phone_number = phone_number
            user.save()

            current_site = get_current_site(request)
            mail_subject = 'Please activate your account'
            message = render_to_string('accounts/account_verification_email.html', {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),

            })
            to_email = email
            send_email = EmailMessage(mail_subject, message, to=[to_email])
            send_email.send()
            # messages.success(request, 'We send verefication mail to you email address.')
            return redirect('/accounts/login/?command=verification&email='+email)
    else:
        form = RegistrationForm()

    context = {'form': form}
    return render(request, 'accounts/register.html', context)


def login(request):
    if request.method == "POST":
        email = request.POST['email']
        password = request.POST['password']

        user = auth.authenticate(email=email, password=password)

        if user is not None:
            try:
                cart = Cart.objects.get(cart_id=_cart_id(request))
                is_cart_item_exists = CartItem.objects.filter(cart=cart).exists()
                if is_cart_item_exists:
                    
                    cart_item = CartItem.objects.filter(cart=cart)
                    variation_products = []
                    for item in cart_item:
                        variation = item.variations.all()
                        variation_products.append(list(variation))
                    
                    cart_item = CartItem.objects.filter(user=user)
                    ex_var_list = []
                    id = []
                    for item in cart_item:
                        existing_variation = item.variations.all()
                        ex_var_list.append(list(existing_variation))
                        id.append(item.id)

                    for pr in variation_products:
                        if pr in ex_var_list:
                            index = ex_var_list.index(pr)
                            item_id = id[index]
                            item = CartItem.objects.get(id=item_id)
                            item.quantity += 1
                            item.user = user
                            item.save()
                        else:
                            cart_item = CartItem.objects.filter(cart=cart)
                            for item in cart_item:
                                item.user = user
                                item.save()
            except:
                pass

            auth.login(request, user)
            messages.success(request, 'You are now logged in.')
            url = request.META.get('HTTP_REFERER')
            try:
                query = requestsLib.utils.urlparse(url).query
                params = dict(x.split('=') for x in query.split('&'))
                if 'next' in params:
                    nextPage = params['next']
                    return redirect (nextPage)
            except:
                return redirect('dashboard')
        else:
            messages.error(request, 'Invalid login credentials')
            return redirect('login')

    return render(request, 'accounts/login.html')


@login_required(login_url='login')
def logout(request):
    auth.logout(request)
    # messages.success(request, 'You are logged out.')
    return redirect('home')


def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Congratulations! Your account is activated')
        return redirect('login')
    else:
        messages.error(request, 'Invalid activation link')
        return redirect('register')

@login_required(login_url='login')
def dashboard(request):
    orders = Order.objects.order_by('-created_at').filter(user_id=request.user.id, is_ordered=True)
    orders_count = orders.count()
    profile = Profile.objects.get(user_id=request.user.id)
    context={'orders_count':orders_count,'profile':profile}
    return render(request, 'accounts/dashboard.html',context)


def forgotPassword(request):
    if request.method == 'POST':
        email = request.POST['email']
        if Account.objects.filter(email=email).exists():
            user = Account.objects.get(email__exact=email)
            
            current_site = get_current_site(request)
            mail_subject = 'Reset password'
            message = render_to_string('accounts/reset_password_email.html', {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),

            })
            to_email = email
            send_email = EmailMessage(mail_subject, message, to=[to_email])
            send_email.send()

            messages.success(request, 'Passowrd reset email has been sent.')
            
            return redirect('login')
        else:
            messages.error(request, 'Account does not exists.')
            return redirect('forgotPassowrd')

    return render (request, 'accounts/forgotPassword.html')

def resetpassword_validate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        request.session['uid'] = uid
        # messages.success(request, 'Please reset your password')
        return redirect('resetPassword')
    else:
        messages.error(request, 'This link has been expired!')
        return redirect('login')

def resetPassword(request):
    if request.method == "POST":
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password == confirm_password:
            uid = request.session.get('uid')
            user = Account.objects.get(pk = uid)
            user.set_password(password)
            user.save()
            messages.success(request, 'Password reset successful')
            return redirect('login')
        else:
            messages.error(request, 'Password do not match!')
            return redirect ('resetPassword')
    else:

        return render (request, 'accounts/resetPassword.html')

@login_required(login_url='login')
def my_orders(request):
    orders = Order.objects.filter(user=request.user, is_ordered=True).order_by('-created_at')
    context ={'orders':orders}
    return render(request, 'accounts/my_orders.html',context)

@login_required(login_url='login')
def edit_profile(request):
    userprofile = get_object_or_404(Profile,user=request.user)
    if request.method == "POST":
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=userprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, "Your profile has been updated")
            return redirect('edit_profile')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=userprofile)
    context ={'user_form':user_form, 'profile_form':profile_form,'userprofile':userprofile }
    return render(request, 'accounts/edit_profile.html',context)

@login_required(login_url='login')
def change_password(request):
    if request.method == "POST":
        current_password = request.POST['current_password']
        new_password = request.POST['new_password']
        confirm_password = request.POST['confirm_password']
        user = Account.objects.get(username__exact=request.user.username)
        if new_password==confirm_password:
            success = user.check_password(current_password)
            if success:
                user.set_password(new_password)
                user.save()

users/templates/users/account.html
{% extends 'main.html'%}
{%block content%}
  <!-- Main Section -->
  <main class="settingsPage profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <a class="tag tag--pill tag--main settings__btn" href="{%url 'edit-account'%}"><i class="im im-edit"></i> Edit</a>
              <img class="avatar avatar--xl dev__avatar" src="{{profile.imageURL}}" />
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.short_intro}}</p>
              <p class="dev__location">Based in {{profile.location}}</p>
              
              <ul class="dev__social">
                {% if profile.social_github%}
                <li>
                  <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="im im-github"></i></a>
                </li>
                {%endif%}
              
                {% if profile.social_twitter%}
                <li>
                  <a title="Twitter" href="{{profile.social_twitter}}" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                {%endif%}
                {% if profile.social_linkedin%}
                <li>
                  <a title="LinkedIn" href="{{profile.social_linkedin}}" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                {%endif%}
                {% if profile.social_website%}
                <li>
                  <a title="Personal Website" href="{{profile.social_website}}" target="_blank"><i class="im im-globe"></i></a>
                </li>
                {%endif%}
              </ul>
 
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
              {{profile.bio}}
            </p>
          </div>
          <div class="settings">
            <h3 class="settings__title">Skills</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{%url 'create-skill'%}"><i class="im im-plus"></i> Add Skill</a>
          </div>

          <table class="settings__table">
            {%for skill in skills%}
            <tr>
              <td class="settings__tableInfo">
                <h4>{{skill.name}}</h4>
                <p>
                  {{skill.description}}
                </p>
              </td>
              <td class="settings__tableActions">
                
                <a class="tag tag--pill tag--main settings__btn" href="{%url 'update-skill' skill.id%}" ><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="{%url 'delete-skill' skill.id%}?next=/account"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>
            {%endfor%}
          </table>

          <div class="settings">
            <h3 class="settings__title">Projects</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{%url 'create-project'%}"><i class="im im-plus"></i> Add Project</a>
          </div>

          <table class="settings__table">
              {%for project in projects%}
            <tr>
              <td class="settings__thumbnail">
                <a href="{%url 'project' project.id %}"><img src="{{project.imageURL}}" alt="Project Thumbnail" /></a>
              </td>
              <td class="settings__tableInfo">
                <a href="{%url 'project' project.id %}">{{project.title}}</a>
                <p>
                  {{project.description|slice:'150'}}
                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="{%url 'update-project' project.id %}"><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="{%url 'delete-project' project.id %}?next=/account"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>
            {%endfor%}
            
          </table>
        </div>
      </div>
    </div>
  </main>
  {%endblock content%}

users/templates/users/inbox.html
 {%extends 'main.html'%}

 {%block content%}

  <!-- Main Section -->
  <main class="inbox my-xl">
    <div class="content-box">
      <h3 class="inbox__title">New Messages(<span>{{unreadCount}}</span>)</h3>
      <ul class="messages">
        {%for message in messageRequests%}
        {%if message.is_read == False %}
        <li class="message message--unread">
        {%else%}
          <li class="message">
        {%endif%}
          <a href="{%url 'message' message.id%}">
            <span class="message__author">{{message.name}}</span>
            <span class="message__subject">{{message.subject}}</span>
            <span class="message__date">{{message.created}}</span>
          </a>
        </li>
       
      {%endfor%}
      </ul>
    </div>
  </main>
{%endblock content%}

users/templates/users/login_register.html
{%extends 'main.html'%}
{%load static%}
{%block content%}
{% if page == 'register'%}

<div class="auth">
    <div class="card">
      
      <div class="auth__header text-center">
        <a href="/">
          <img src="{%static 'images/icon.svg'%}" alt="icon" />
        </a>
        <h3>Register an Account</h3>
        <p>Create a new developer account</p>
      </div>
      {% if messages %} {% for message in messages %}
      <div class="alert alert--{{message.tags}}">
        <p class="alert__message">{{message}}</p>
        <button class="alert__close">⨯</button>
      </div>
      {% endfor %} {% endif %} 
      <form method="POST" action="{%url 'register'%}" class="form auth__form">
        {%csrf_token%}
        {%for field in form%}        
        <!-- Input:Text -->
        <div class="form__field">
          <label for="formInput#text">{{field.label}}: </label>
          {{field}}
          <!-- {%if field.help_text%}
            <small>{{field.help_text}}</small>
          {%endif%} -->

          {% for error in field.errors%}
          <p style="color:red">{{error}}</p>
          {%endfor%}
        </div>
        {%endfor%}
       
        <div class="auth__actions">
          <input class="btn btn--sub btn--lg" type="submit" value="Sign  In" />
        </div>
      </form>
      <div class="auth__alternative">
        <p>Already have an Account?</p>
        <a href="{% url 'login'%}">Log In</a>
      </div>
    </div>
  </div>
{%else%}

<div class="auth">
    <div class="card">
      <div class="auth__header text-center">
        <a href="/">
          <img src="{% static 'images/icon.svg'%}" alt="icon" />
        </a>
        <h3>Account Login</h3>
        <p>Hello Developer, Welcome Back!</p>
      </div>
      {% if messages %} {% for message in messages %}
      <div class="alert alert--{{message.tags}}">
        <p class="alert__message">{{message}}</p>
        <button class="alert__close">⨯</button>
      </div>
      {% endfor %} {% endif %} 
      <form action="" method = "POST" class="form auth__form">
        {%csrf_token%}
        <!-- Input:Username -->
        <div class="form__field">
          <label for="formInput#text">Username: </label>
          <input
            class="input input--text"
            id="formInput#text"
            type="text"
            name="username"
            placeholder="Enter your username..."
          />
        </div>

        <!-- Input:Password -->
        <div class="form__field">
          <label for="formInput#password">Password: </label>
          <input
            class="input input--password"
            id="formInput#passowrd"
            type="password"
            name="password"
            autocomplete="on"
            placeholder="••••••••"
          />
        </div>
        <div class="auth__actions">
          <input class="btn btn--sub btn--lg" type="submit" value="Log In" />
          <a href="{%url 'reset_password'%}">Forget Password?</a>
        </div>
      </form>
      <div class="auth__alternative">
        <p>Don’t have an Account?</p>
        <a href="{%url 'register'%}">Sign Up</a>
      </div>
    </div>
  </div>
{%endif%}

{%endblock content%}

users/templates/users/message.html
 {%extends 'main.html'%}

 {%block content%}
  <!-- Main Section -->
  <main class="messagePage my-xl">
    <div class="content-box">
      <div class="message">
        <a class="backButton" href="{%url 'inbox'%}"><i class="im im-angle-left"></i></a>
        <h2 class="message__subject">{{message.subject}}</h4>
          {%if message.sender%}
          <a href="{%url 'user-profile' message.sender.id %}" class="message__author">{{message.sender}}</a>
          {%else%}
          <p class="message__author">{{message.name}}</p>
          {%endif%}
          <p class="message__date">{{message.created}}</p>
          <div class="message__body">
            {{message.body|linebreaksbr}}
          </div>
      </div>
    </div>
  </main>
  {%endblock content%}

users/templates/users/message_form.html
 {%extends 'main.html'%}

 {%block content%}
  <!-- Main Section -->
  <main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{%url 'user-profile' recipient.id%}"><i class="im im-angle-left"></i></a>
            <br>

            <form class="form" method="POST">
                {%csrf_token%}
                {%if request.user.is_authenticated == False%}
                <!-- Input:Text -->
                <div class="form__field">
                    <label for="formInput#text">{{form.name.label}}</label>
                    {{form.name}}
                    
                </div>

                <div class="form__field">
                    <label for="formInput#text">{{form.email.label}}</label>
                    {{form.email}}
                </div>

                {%endif%}
                <!-- Input:Text -->
                <div class="form__field">
                    <label for="formInput#text">{{form.subject.label}}</label>
                    {{form.subject}}
                </div>

                <div class="form__field">
                    <label for="formInput#text">{{form.body.label}}</label>
                    {{form.body}}
                </div>
                
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>
 {%endblock content%}

users/templates/users/profile_form.html
{% extends 'main.html'%}

{% block content %}

<!-- Main Section -->
<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{%url 'account'%}"><i class="im im-angle-left"></i></a>
            <br>

            <form class="form" method="POST" action="{%url 'account'%}" , enctype="multipart/form-data">
                {% csrf_token %}
                {%for field in form%}
                <!-- Input:Text -->
                <div class="form__field">
                    <label for="formInput#text">{{field.label}} </label>
                    {{field}}
                </div>
                {%endfor%}

               
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>
{% endblock content %}

users/templates/users/profiles.html
{% extends 'main.html'%}
{%block content%}
 <!-- Main Section -->
 <main class="home">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
          <h2>FROM AROUND THE WORLD</h2>
        </div>

        <div class="hero-section__search">
          <form id="searchForm" class="form" action="{%url 'profiles'%}" method="get">
            <div class="form__field">
              <label for="formInput#search">Search Developers </label>
              <input class="input input--text" id="formInput#search" type="text" name="search_query"
                value="{{search_query}}" placeholder="Search by developer name" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
      <div class="container">
        <div class="grid grid--three">
          {% for profile in profiles %}
            <div class="column card">
            <div class="dev">
              <a href="{% url 'user-profile' profile.id %}" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="{{profile.imageURL}}" alt="image" />
                  <div class="dev__meta">
                    <h3>{{profile.name}}</h3>
                    <h5>{{profile.short_intro|slice:"60"}}</h5>
                  </div>
                </div>
                <p class="dev__info">
                  {{profile.bio|slice:"150"}}
                </p>
                <div class="dev__skills">
                    {% for skill in profile.skill_set.all|slice:"5" %}
                  <span class="tag tag--pill tag--main">
                    <small>{{skill.name}}</small>
                  </span>
                  {%endfor%}
                  
                </div>
              </a>
            </div>
          </div>
          {%endfor%}
         >
        </div>
      </div>
    </section>
    {%include 'pagination.html' with queryset=profiles custom_range=custom_range%}
  </main>
{%endblock content%}